/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: savscarlett (https://sketchfab.com/savscarlett)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/capybara-hot-spring-9a804773229f4f52a5dc008fd161ece4
title: Capybara Hot Spring
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./capybara.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <mesh geometry={nodes.BambooSpout02_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.BambooSpout01_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.WaterFlow02_LP_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.WaterFlow01_LP_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.DisplayBase_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_10_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_05_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_08_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_11_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_04_LP_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.Rock_12_LP_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.Rock_13_LP_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.Rock_14_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_15_LP_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.Rock_01_LP_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.Rock_07_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_09_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_06_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_02_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_00_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.Rock_03_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.GroundOrangeStalk_01_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.GroundOrange_01_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.GroundOrange_02_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.GroundOrangeStalk_02_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.GroundOrange_03_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.GroundOrangeStalk_03_LP_Environment01_Mat_0.geometry} material={materials.Environment01_Mat} />
          <mesh geometry={nodes.BathTubBody_LP_Capybaras_Mat_0.geometry} material={materials.Capybaras_Mat} />
          <mesh geometry={nodes.MetalRingTop_LP_Capybaras_Mat_0.geometry} material={materials.Capybaras_Mat} />
          <mesh geometry={nodes.MetalRingBottom_LP_Capybaras_Mat_0.geometry} material={materials.Capybaras_Mat} />
          <mesh geometry={nodes.BigCapyBody_LP_Capybaras_Mat_0.geometry} material={materials.Capybaras_Mat} />
          <mesh geometry={nodes.BigCapyEyes_LP_Capybaras_Mat_0.geometry} material={materials.Capybaras_Mat} />
          <mesh geometry={nodes.SmallCapy_LP_Capybaras_Mat_0.geometry} material={materials.Capybaras_Mat} />
          <mesh geometry={nodes.HeadOrange_LP_Capybaras_Mat_0.geometry} material={materials.Capybaras_Mat} />
          <mesh geometry={nodes.OrangeStalk_LP_Capybaras_Mat_0.geometry} material={materials.Capybaras_Mat} />
          <mesh geometry={nodes.Leaf_01_LP_Capybaras_Mat_0.geometry} material={materials.Capybaras_Mat} />
          <mesh geometry={nodes.Leaf02_LP_Capybaras_Mat_0.geometry} material={materials.Capybaras_Mat} />
          <mesh geometry={nodes.LightSpeck01_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.LightSpeck02_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.LightSpeck03_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.LightSpeck04_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.LightSpeck05_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
          <mesh geometry={nodes.LightSpeck06_Environment02_Mat_0.geometry} material={materials.Environment02_Mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/capybara.glb')
